name: Deployment Workflow
on: 
  push:
    branches: [ main ]

jobs: 
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy to ocjoggers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.OCJ_HOST }}
        username: ${{ secrets.OCJ_USER }}
        key: ${{ secrets.OCJ_SECRET }}
        passphrase: ${{ secrets.OCJ_PASS }}
        port: 22
        script: | 
          cd /var/www/laravel
          git pull origin main
          php artisan cache:clear
          php artisan view:cache
          php artisan config:cache
          php artisan event:cache
          php artisan route:cache
          php artisan route:clear
          git status
