name: Deployment Workflow
on: [push]

jobs: 
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy to ocjoggers
      uses: appleboy/ssh-action@master
      with:
        host: 165.232.140.240
        username: ocjoggers
        key: ${{ secrets.OCJ_SECRET }}
        port: 22
        script: | 
          cd /home
          git pull origin master
          git status
